[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Paulo Coelho <9609090+prscoelho@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
